### ISSUE TITLE
"clangd was not found on your PATH" but it's not true

### ISSUE THREAD

**Issue by haomingw** [clangd/coc-clangd#211]
I have `clangd` installed and `which clangd` gives `/usr/local/bin/clangd`. When I open a cpp file, it shows the following error message:
```
[coc.nvim] clangd was not found on your PATH. :CocCommand clangd.install will install 11.0.0.
```
Then I ran `:CocCommand clangd.install` as suggested, in :message I have
```
[coc.nvim] Downloading clangd-mac-11.0.0.zip...
[coc.nvim] Extracting clangd-mac-11.0.0.zip...
client coc abnormal exit with: -1
client coc stopped!
starting coc.nvim service
[coc.nvim] clangd was not found on your PATH. :CocCommand clangd.install will install 11.0.0.
```

I tested on latest neovim, but for vim 8.2 it's the same.

**System information**
Clangd version (from the log, or `clangd --version`):
```
clangd version 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06)
```

clangd extension version (from `:CocInfo`):
```
vim version: NVIM v0.4.4
node version: v14.16.0
coc.nvim version: 0.0.80-fedaf52837
coc.nvim directory: /Users/haoming/.vim/bundle/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-03-12T21:06:56.537 INFO (pid:3315) [services] - registered service "languageserver.golang"
2021-03-12T21:06:56.613 INFO (pid:3315) [plugin] - coc.nvim 0.0.80-fedaf52837 initialized with node: v14.16.0 after 124ms
2021-03-12T21:07:02.191 INFO (pid:3315) [attach] - receive notification: showInfo []
```

Operating system: `macOS Big Sur`

**Comment by fannheyward** [comment]
Do you have set `clangd.path` in your coc-settings.json?

**Comment by haomingw** [comment]
> Do you have set `clangd.path` in your coc-settings.json?

After running `CocCommand clangd.install`, I have `clangd.path` pointing to the downloaded clangd binary (`~/.config/coc/extensions/coc-clangd-data/install/11.0.0/clangd_11.0.0/bin/clangd`), but still the same error

**Comment by haomingw** [comment]
FYI on my linux it works fine, my `clangd` (now the one downloaded by `CocCommand`) is well detected

**Comment by fannheyward** [comment]
I'm using clangd with coc-clangd on macOS, can't reproduce your issue. Try to delete `clangd.path` in your coc-settings.json, don't run `CocCommand clangd.install`.

**Comment by haomingw** [comment]
I get it, my vimrc is setting `clangd.path` to the homebrew clangd, since I am using another clangd, it's normal that clangd cannot be found, and it's visible in `coc-settings.json`. Your comments made me think if it's because of my personal settings. Thank you very much for your help!

**Comment by CroMarmot** [comment]
"clangd was not found on your PATH" This error message is inaccurate and misleading sometimes
---

How I encountered this problem:.

I installed clang19 using `CocCommand clangd.install` through the guide(https://github.com/clangd/coc-clangd/blob/master/README.md#quick-start).

But the code uses bits/stdc++.h, which gives an error in vim: “not found”.

So I added the corresponding `-I` configuration (https://github.com/clangd/clangd/issues/938#issuecomment-983269766) to the `.clangd` configuration file, but it still reported the error

According to the command to check the error log (https://github.com/neoclide/coc.nvim/issues/2505#issuecomment-1272877120), I sifted through and found that removing `-resource-dir=` compiles correctly on the command line.

So, I deleted the folder corresponding to `clang19` (moved it to `-bak`), and got the error “clangd was not found on your PATH”, but my PATH is fine!

Found this issue: https://github.com/clangd/coc-clangd/issues/211

After removing `clangd.path` from `CocConfig` (was it added by clangd.install?). , it works fine.

---

Expect
1. add some `clangd.uninstall` function to accomplish symmetrical operation.
2. when `clangd.path` cannot be found, report the error correctly instead of “clangd was not found on your PATH”.
