### ISSUE TITLE
incremental highlighting support

### ISSUE THREAD

**Issue by fannheyward** [clangd/coc-clangd#29]
From https://github.com/clangd/coc-clangd/pull/27#issuecomment-602808843, clangd 10+ will do incremental highlighting support.

This should fix https://github.com/jackguo380/vim-lsp-cxx-highlight/issues/20

> Maybe having coc-clangd cache previous highlighting messages then calling lsp_cxx_hl#hl#notify_symbols would fix this issue.

**Comment by sam-mccall** [comment]
A couple of related issues here:
 - the old notification-based protocol ("theia protocol"). The protocal was always defined as incremental. Clangd 9 sent all tokens every time. Clangd 10 sends only the changed ones. 008da37c06d1068ce207fff840468fe307927092 fixes coc-clangd to apply the diffs.
 - the new request-based protocol (will be in LSP 3.16). Clangd will support both absolute and incremental requests. We should add support for this (probably to coc.nvim itself rather than coc-clangd).

**Comment by sam-mccall** [comment]
@fannheyward could you push a new release here so we can pick up this fix? (or grant https://www.npmjs.com/~sam-mccall rights to do that) Thanks!

(After that I'm not sure if you want to close this issue, or if you want to use it for work on supporting the new protocol)

**Comment by fannheyward** [comment]
New version has released, also invite you to npmjs as a maintainer.

**Comment by sam-mccall** [comment]
@fannheyward thanks a lot!
