### ISSUE TITLE
Implement Semantic Highlighting since it's no longer supported by vim-lsp-cxx-highlight

### ISSUE THREAD

**Issue by kirillbobyrev** [clangd/coc-clangd#369]
Context: https://github.com/jackguo380/vim-lsp-cxx-highlight/commit/dd9746f32b8128ddf67846636b559623a318109b

> The latest versions of clangd (13+) are no longer compatible with vim-lsp-cxx-highlight
> There are have no plans to fix this, ever, instead please ask your LSP client to support Semantic Tokens

**Comment by erwin** [comment]
When we are using `let g:coc_default_semantic_highlight_groups = 1` how do we identify the syntax group that is being used to perform the highlight?

With normal Vim syntax highlights, I can use:

```
nnoremap <F5> :echo synIDattr(synID(line('.'), col('.'), 1), 'name') <CR>
```

![image](https://user-images.githubusercontent.com/11534217/140594018-8f1eb3ba-256b-4e15-81c1-59afbc0d955d.png)

However when using COCs semantic_highlight_groups (which look great!) there must be a different way to access the name of the group used in the highlight (so that I can appropriately improve my color scheme).

`coc-highlights` describes some of the semantic highlights, but doesn't talk about how to determine the highlight used for the character under the cursor.

**Comment by interruptinuse** [comment]
@erwin Are you looking for something like [this](https://stackoverflow.com/a/37040415)?

```vim
function! SynGroup()                                                            
    let l:s = synID(line('.'), col('.'), 1)                                       
    echo synIDattr(l:s, 'name') . ' -> ' . synIDattr(synIDtrans(l:s), 'name')
endfun
```

**Comment by erwin** [comment]
Yes, something similar except that works on *CocSem_** highlight groups.
