### ISSUE TITLE
Can it add a options to disalbe snippet completions?

### ISSUE THREAD

**Issue by fcying** [clangd/coc-clangd#59]
ex: `clangd.disableSnippet`,  default `false`?

**Comment by sam-mccall** [comment]
Try adding `--function-arg-placeholders=0` to clangd.args.

**Comment by fcying** [comment]
I add `"clangd.arguments": ["--function-arg-placeholders=0"],` into `coc-settings.json`, but it have snipper also.
![image](https://user-images.githubusercontent.com/106934/83724264-8d942400-a672-11ea-899f-80a85261b9ee.png)

**Comment by sam-mccall** [comment]
OK, what exactly do you mean by snippet completions that you want to disable?

Do you still want `if`, just not completing the rest of the statement?
Do you want completing `std::vector` to include `< {type} >` and completing functions to include the arg list?

**Comment by fcying** [comment]
just type `if`, have not any snipet completions, ex:
![image](https://user-images.githubusercontent.com/106934/84149764-8bc3c980-aa93-11ea-9f9e-ef13895034b5.png)
completing `std::vector`  `< {type} >` and completing functions to include the arg list also no need.

Because I also install `ultisnips` for custom some snipets, snipet from clangd is not need.

**Comment by sam-mccall** [comment]
OK, we can disable *all* snippets in code completion results by having the client claim it doesn't support snippets in capabilities.

@fannheyward do you think it makes sense to have this option in coc.nvim itself, rather than on each extension? Currently `snippetSupport: true` is set by `CompletionItemFeature` in `language-client/client.ts`.

> completing std::vector < {type} > and completing functions to include the arg list also no need.
> Because I also install ultisnips for custom snipets, not need default snipet from clangd

I don't really see how this follows - UltiSnips doesn't know what arguments the function you just completed adds, so can't provide appropriate placeholders. But signaturehelp should work well enough...

**Comment by fannheyward** [comment]
I prefer to add this option in extension, there are `commitCharactersSupport`, `deprecatedSupport` etc in `CompletionItemFeature`, if we add option for snippet, how about others? I don't think this option is widely used.

**Comment by fannheyward** [comment]
Add `clangd.snippetSupport`, default `true`.

**Comment by fannheyward** [comment]
coc has added `disableSnippetCompletion` configuration,  `clangd.snippetSupport` has been removed, use `clangd.disableSnippetCompletion` instead.
