### ISSUE TITLE
Implementation provider not found for current document, although definition is found

### ISSUE THREAD

**Issue by lucamu** [clangd/coc-clangd#78]
I have been looking for info on this everywhere, without much success so far, so I am opening this issue.

I just installed coc, clangd and coc-clangd on a fresh nvim install and configured keybinds, etc. and I have the following keybinds in my init.vim:
`nmap <silent> gd <Plug>(coc-definition)
 nmap <silent> gy <Plug>(coc-type-definition)
 nmap <silent> gi <Plug>(coc-implementation)
 nmap <silent> gr <Plug>(coc-references)
`
I am able to go to the definition of any function, be it my own or one in a library. However, I am unable go to the function's implementation. Whenever I do, I get the error message "Implementation provider not found for current document" (it looks like [this](https://imgur.com/a/oahKvh0) if that is any useful). I feel like when I'm able to find the definition of the function, I should also be able to find its implementation.

**Logs**
I wasn't able to get any meaningful information from either coc or clangd log.

**System information**
Clangd version : 10.0.1
coc.nvim version: 0.0.78-9f9d8a32c4
Operating system: linux

**Comment by fannheyward** [comment]
It's not a bug, clangd doesn't support `textDocument/Implementation` yet.

**Comment by tao-guo** [comment]
I found out that if both Foo.cpp and Foo.h are parsed, "gd" will go back and forth between implementation and declaration among the two files. Since Foo.h is usually included in Foo.cpp, there is no issue if Foo.cpp is being opened. However, if only Foo.h is being opened, you will not find the implementation from coc-definition.

Right now, I can manually switch to  Foo.cpp by using clangd.switchSourceHeader and go back to search again to find the implementation. It is kind of annoying however. Is there a way to activate the Foo.cpp parsing automatically or ask coc-clangd to do it in the background?

**Comment by kadircet** [comment]
You need to have a compilation database to tell clangd about projects in your file. Then it will index them in the background automatically as they change. See compile_commands.json part in http://clangd.llvm.org/installation.html

**Comment by tao-guo** [comment]
I have already enabled the background indexing:
cat ~/.vim/coc-settings.json
{
    "suggest.autoTrigger": "always",
    "suggest.triggerCompletionWait": "300",
    "coc.preferences.useQuickfixForLocations": true,
    "clangd.arguments": ["--background-index"]
}
However, unlike ccls's index caching, clangd's seems very small, and I still need to wait for the full parsing to finish every time.

**Comment by kadircet** [comment]
yes, symbol index and parsing of a new file are totally different things. currently clangd doesn't cache any information to speed-up initial parsing of a file.

**Comment by bneradt** [comment]
Just to emphasize this in case it's helpful to others: @tao-guo 's comment is extremely helpful. I hope that a lot of people trying to jump to the implementation find this, because it wasn't obvious to me that `gi` wouldn't work but multiple calls `gd` would shift between declaration and implementation:

> I found out that if both Foo.cpp and Foo.h are parsed, "gd" will go back and forth between implementation and declaration among the two files. Since Foo.h is usually included in Foo.cpp, there is no issue if Foo.cpp is being opened. However, if only Foo.h is being opened, you will not find the implementation from coc-definition.
