### ISSUE TITLE
coc-clangd quick-start set configuration

### ISSUE THREAD

**Issue by atticus-sullivan** [clangd/coc-clangd#82]
Hi,
I'm a newbie with coc, so maybe it is obvious, maybe it is a good question.

As far as I understood it, installing `coc-clangd` provides the interface to be able to use `clangd` from inside `coc` and by entering `:CocCommand clangd.install` the `clangd` language server (independent of `coc`) is installed and started by default when opening a C/C++ file.

Now my problem is that I want to pass some config to `coc-clangd` (at least I think it's `coc-clangd` and not `clangd`) for example `clangd.disableSnippetCompletion`.

How do I do this?

(I thought I'd have to put it into the `coc-settings.json` file, but above at [https://github.com/clangd/coc-clangd#quick-start](https://github.com/clangd/coc-clangd#quick-start) there is the Note
> If you've configured clangd as a languageServer in coc-settings.json, you should remove it to avoid running clangd twice!

So I think set this configuration option cannot be done in `coc-settings.json`)

**Comment by Lythenas** [comment]
You can put all the settings listed in the readme into `coc-settings.json`.

With `coc` it is also possible to manually configure any language server (see the example in the coc readme). The note simply says that you should not use the manual configuration if you use this extension because this extension will setup clangd for you.

**Comment by atticus-sullivan** [comment]
Thanks for the quick response, so I simply put
```
{
    clangd.disableSnippetCompletion = true
}
```
into the `coc-settings.json` file (and it seems to be working).

Just being curious, the alternative to using `:CocCommand clangd.install` would be to install clangd without the help of vom/coc and in that case I would have to put the language server entry into the `coc-settings.json` file right?

Oh, and is `clang-tidy` by `:CocCommanf clangd.install` installed by default or has the user to install this manually by himself?

**Comment by Lythenas** [comment]
I use `let g:coc_global_extensions = [ 'coc-clangd', ... ]` in my vimrc so that I don't have to remember to install all the extensions on other PCs I use.

If you manually setup clangd with coc some of the extensions to the lsp protocol probably won't work but I think you will still get code completion and diagnostics etc. because they are supported by coc directly. Also you have to install clangd yourself.

The way I understand it is that clang-tidy is integrated into clangd but I'm not entirely sure. I use

```json
    "clangd.arguments": [
        "--background-index",
        "--clang-tidy"
    ]
```

in my `coc-settings.json`. This enables the clang-tidy checks (and `--background-index` persists the index to disk).

**Comment by atticus-sullivan** [comment]
Oh thanks this is a nice trick, and thanks for improving my understanding of coc and language servers.
